### ISSUE TITLE
Error when the VM already exist in netbox

### ISSUE THREAD

**Issue by Sabrimjd** [smutel/terraform-provider-netbox#130] opened 2022-08-22 14:10 UTC
### Netbox version

```
v3.1.9
```

### Terraform version

```
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/vsphere v1.24.3
+ provider registry.terraform.io/smutel/netbox v4.0.1

```

### Provider version

```paste below
+ provider registry.terraform.io/smutel/netbox v4.0.1
```

### Affected Data(s) / Resource(s)

* netbox_virtualization_vm 

### Terraform Configuration Files

```hcl
resource "netbox_virtualization_vm" "netbox_vm_HUWTESFR1-001" {
  name        = "HUWTESFR1-001"
  comments    = "TESTTTT"
  disk        = "91"
  memory      = "4096"
  vcpus       = "2"
  cluster_id  = data.netbox_virtualization_cluster.vc_huwtesfr1-001.id
  tenant_id   = data.netbox_tenancy_tenant.tt_huwtesfr1-001.id
  ### role_id is not exported by the api... we have to hardcode it for now
  role_id     = 14
  platform_id = data.netbox_dcim_platform.dp_huwtesfr1-001.id
}

```

### Terraform Output

```paste below
module.all.netbox_virtualization_vm.netbox_vm_HUWTESFR1-001: Creating...
╷
│ Error: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}
│ 
│   with module.all.netbox_virtualization_vm.netbox_vm_HUWTESFR1-001,
│   on all/HUWTESFR1-001.tf line 43, in resource "netbox_virtualization_vm" "netbox_vm_HUWTESFR1-001":
│   43: resource "netbox_virtualization_vm" "netbox_vm_HUWTESFR1-001" {
│ 
╵

```

### Actual Behavior

Error when the VM already exist in netbox

### Expected Behavior

Know the state and updatethe data if needed.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by smutel** [comment] 2022-08-22 15:08
Hello,

The first creation was done manually or with the provider ?

**Comment by smutel** [comment] 2022-08-26 07:10
Up

**Comment by Sabrimjd** [comment] 2022-08-30 13:07
Hello @smutel with the provider

**Comment by smutel** [comment] 2022-08-30 14:08
Is-it possible to update Netbox to v3.1.11 ?
I am not able to reproduce this issue.

**Comment by Sabrimjd** [comment] 2022-08-30 14:52
Hello, will try with an updated Netbox. Thanks for your provider it works very well :).

Do you think it is possible to force overwrite if the resource already exists (but not in the tfstate) ?

**Comment by smutel** [comment] 2022-08-30 16:27
It's not exactly the behavior of the terraform providers.

If the object does not exist, the provider should create it. If not you should use terraform import to import that existing resource and manage it through terraform.

**Comment by smutel** [comment] 2022-09-23 18:56
I close the issue. Feel free to re-open it if your issue is still there.

**Closed by smutel** 2022-09-23 18:56 UTC
Labels: bug
